# Generated by Django 5.0.5 on 2024-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('volunteer', 'Volunteer'), ('student', 'Student'), ('other', 'Other')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
